# 4. 파이토치 기본
## 4.1 텐서

In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(5,4)

In [3]:
print(x)

tensor([[8.9082e-39, 1.0286e-38, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39, 9.6429e-39],
        [1.0653e-38, 1.0469e-38, 4.2246e-39, 1.0378e-38]])


In [4]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.zeros(2)

tensor([0., 0.])

In [6]:
torch.rand(5,6)

tensor([[0.8247, 0.1895, 0.1080, 0.8054, 0.3347, 0.2016],
        [0.5404, 0.6099, 0.8351, 0.7964, 0.1402, 0.5730],
        [0.2102, 0.3128, 0.4704, 0.0214, 0.1214, 0.1650],
        [0.9212, 0.0139, 0.7412, 0.9744, 0.6450, 0.3697],
        [0.5179, 0.4304, 0.4282, 0.4637, 0.5445, 0.7213]])

In [7]:
l = [13,4]
r = np.array([4,56,7])

In [8]:
torch.tensor(l)

tensor([13,  4])

In [9]:
torch.tensor(r)

tensor([ 4, 56,  7], dtype=torch.int32)

In [10]:
x.size()

torch.Size([5, 4])

In [11]:
x.size()[1]

4

In [12]:
x.size(1)

4

In [13]:
type(x)

torch.Tensor

In [14]:
x = torch.rand(2,2) # 2x2 랜덤 행렬
y = torch.rand(2,2) # 2x2 랜덤 행렬
x+y

tensor([[1.2839, 0.9063],
        [0.3118, 0.8667]])

In [15]:
torch.add(x,y)

tensor([[1.2839, 0.9063],
        [0.3118, 0.8667]])

In [16]:
y.add(x)

tensor([[1.2839, 0.9063],
        [0.3118, 0.8667]])

In [17]:
y.add_(x)

tensor([[1.2839, 0.9063],
        [0.3118, 0.8667]])

In [18]:
x = torch.rand(8,8)
print(x.size())

torch.Size([8, 8])


In [19]:
a = x.view(64)
print(a.size())

torch.Size([64])


In [20]:
b = x.view(-1,4,4)
print(b.size())

torch.Size([4, 4, 4])


In [21]:
y = x.numpy()
type(y)

numpy.ndarray

In [22]:
x = torch.ones(1)
print(x.item())

1.0
